version: "3.9"

services:
  postgres_local:
    image: postgres:16
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_DB: registro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
    - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
